version: "3.8"
services:
  web:
    container_name: email_template_tester_web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    container_name: email_template_tester_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_EMAIL=username@gmail.com
      - SMTP_USER=username@gmail.com
      - SMTP_PASS=password

